import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'


const bearer = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGl0YXMiOjUsIm5hbWFEZXBhbiI6IlN1Yi1EaXN0cmlidXRvciIsIm5hbWFCZWxha2FuZyI6IjU1MDYiLCJzdXJlbEtvbnRhayI6InN1YmRpczU1MDZAbWFpbC5jb20iLCJqYWJhdGFuIjo0LCJzdGF0dXNLZWFrdGlmYW4iOnRydWUsInN0YXR1c0hhbnR1IjpmYWxzZSwibmFtYURvbXBldCI6IjI1NDQ0Mzg5Iiwic3VyZWwiOiJvZmZpY2VzdWJkaXM1NTA2QG1haWwuY29tIiwiQ29tcGFueSI6dHJ1ZSwiaWF0IjoxNjI2MzQxODAzLCJleHAiOjE2MjY0MjgyMDN9.9oVd_ntTqEiP1HpPjjE2059CCp3KomHhGaixrFhP4x4";

export async function getServerSideProps(context) {
  const res = await fetch(`https://wwb6j89602.execute-api.ap-southeast-1.amazonaws.com/dev/order?as=buyer`, {
    method: 'GET',
    withCredentials: true,
    credentials: 'include',
    headers: {
      'Authorization': bearer,
      // 'X-FP-API-KEY': 'iphone', //it can be iPhone or your any other attribute
      'Content-Type': 'application/json'
    }
  })
  const data = await res.json()
  console.log("getServerSideProps", { data })
  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: { data }, // will be passed to the page component as props
  }
}

export default function Home({ data: { data } }) {
  function formattingNumber(value) {
    if (value) return value.toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ".");
    return 0
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3> Hello World.</h3>
        <Link href="/tv-show" className={styles.title}>
          <a style={{ fontWeight: "bold", color: "#0070f3" }}>Go to TV Shows Page</a>
        </Link>

        {data?.rows &&
          <div style={{ marginTop: "2.5rem" }}>
            <p>GET /dev/order?as=buyer :: count {data?.count}</p>
            {
              data?.rows.map((d) => {
                return (
                  <div key={d?.id} style={{
                    display: "flex",
                    justifyContent: "space-between",
                    width: "768px",
                  }}>
                    <p>Nomor Pesanan: {d?.nomorPesanan}</p>
                    <span>
                      <p>Jumlah: {formattingNumber(d?.jumlah)}</p>
                      <p>Total Harga: {formattingNumber(d?.totalHarga)}</p>
                    </span>
                  </div>
                )
              })
            }
          </div>}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div >
  )
}
